- version: 2
- checks: Configuration of maintainability checks
  argument-count:
    config:
      threshold: 8
- plugins: Enable optional engines to run in addition to your analysis
  bandit:
    enabled: true