version: "3"

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - catalog-network
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - catalog-network
    ports:
      - 8081:8081

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - catalog-network

  catalog-api:
    build:
      context: catalog
      dockerfile: Dockerfile
    container_name: catalog-api
    networks:
      - catalog-network


networks:
  catalog-network:
    driver: bridge