version: "3"

services:
  catalog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-api
    networks:
      - catalog-network


networks:
  catalog-network:
    driver: bridge