# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from catalog.src.protos import something_pb2 as something__pb2


class DeleteEpisodeTranscriptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteTranscriptions = channel.unary_unary(
                '/DeleteEpisodeTranscription/DeleteTranscriptions',
                request_serializer=something__pb2.DeleteRequest.SerializeToString,
                response_deserializer=something__pb2.DeleteReply.FromString,
                )


class DeleteEpisodeTranscriptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteTranscriptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeleteEpisodeTranscriptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteTranscriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTranscriptions,
                    request_deserializer=something__pb2.DeleteRequest.FromString,
                    response_serializer=something__pb2.DeleteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeleteEpisodeTranscription', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeleteEpisodeTranscription(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteTranscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeleteEpisodeTranscription/DeleteTranscriptions',
            something__pb2.DeleteRequest.SerializeToString,
            something__pb2.DeleteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
